server:
  port: 8080
  servlet:
    contextPath: "/creditcard-integrator"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/credit-card-integrator?serverTimezone=UTC"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    initialization-mode: "always"
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      #initialize-schema: always
      platform: mysql
    job:
      enabled: false
  springdoc:
    swagger-ui:
      path: /swagger-ui.html

integration:
  file:
    students:
      #source: src/test/resources/lista_alunos.txt
      source: lista_alunos.txt
      delimiter: \t
      load: true   # Make true to load initial batch load from students
      chunk-size: 1000