# Server
server:
  port: 8080
  servlet:
    contextPath: "/creditcard-integrator"

# Database
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/credit-card-integrator?serverTimezone=UTC"
    username: "root"
    password: "admin"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    initialization-mode: "always"
  jpa:
    open-in-view: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update